[package]
name = "google-meme-generator"
version = "0.1.0"
authors = ["mlunax <lunax@mlunax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
imageproc = "0.22.0"
rusttype = "0.9.2"